Repository 2024-SummerBootcamp-Team/frontend, pull requests merged in 2024-07, with the labels that each got.

#5 [design] v0 테스트 완료 및 캐릭터 선택 페이지 퍼블리싱
  .pnp.cjs
  package.json
  postcss.config.js
  src/App.css
  src/App.tsx
  src/components/Navbar.tsx
  src/pages/Main.tsx
  tailwind.config.js
  yarn.lock
Labels: 🎨 Html&css

#7 [design] 퍼블리싱 테스트
  .pnp.cjs
  package.json
  src/App.css
  src/App.tsx
  src/components/Card.tsx
  src/index.css
  src/pages/Main.tsx
  src/pages/Test.tsx
  src/pages/Test2.tsx
  src/styles/card.css
  src/styles/test.css
  tailwind.config.js
  yarn.lock
Labels: 🎨 Html&css

#10 [design] 메인페이지 퍼블리싱
  .pnp.cjs
  aos.d.ts
  package-lock.json
  package.json
  src/App.css
  src/components/CharacterCard.tsx
  src/components/Navbar.tsx
  src/pages/Main.tsx
  src/styles/card.css
  src/styles/test.css
  tailwind.config.js
  yarn.lock
Labels: 🎨 Html&css

#12 [design] 채팅페이지 퍼블리싱
  .pnp.cjs
  .yarnrc.yml
  deps/_metadata.json
  deps/package.json
  src/App.tsx
  src/components/AudioPlayer.tsx
  src/pages/Chat.tsx
Labels: 🎨 Html&css

#14 [design] 저장한 음성 및 이미지 페이지 퍼블리싱
  .pnp.cjs
  src/App.tsx
  src/pages/Practice.tsx
Labels: 🎨 Html&css

#15 [feat] 채팅기능 구현
  .pnp.cjs
  index.html
  package.json
  src/App.tsx
  src/api/axios.ts
  src/api/chat.ts
  src/api/voices.ts
  src/components/CharacterCard.tsx
  src/pages/Chat.tsx
  yarn.lock
Labels: ✨ Feature

#18 [setting] env 설정
  .gitignore
  src/api/axios.ts
  src/pages/Chat.tsx
  src/vite-env.d.ts
  yarn.lock
Labels: ⚙ Setting

#20 [feat] 채팅, tts 동시 스트림 기능구현
  src/api/chat.ts
  src/components/AudioPlayer.tsx
  src/pages/Chat.tsx
Labels: ✨ Feature

#23 [feat] 음성 및 이미지 페이지 UI 수정 및 이동 기능 구현
  .pnp.cjs
  src/api/images.ts
  src/api/voices.ts
  src/components/Navbar.tsx
  src/pages/Practice.tsx
  yarn.lock
Labels: ✨ Feature

#24 [feat] 채팅방별 TTS 목록 기능구현
  .pnp.cjs
  package.json
  src/App.tsx
  src/api/images.ts
  src/api/voices.ts
  src/components/Navbar.tsx
  src/pages/Chat.tsx
  src/pages/ListBoard.tsx
  yarn.lock
Labels: ✨ Feature

#25 [feat] TTS 다운로드 기능구현
  src/api/voices.ts
  src/pages/Chat.tsx
  tailwind.config.js
Labels: ✨ Feature

#28 [feat] 캐릭터별 채팅방 생성 기능구현
  src/App.tsx
  src/api/chat.ts
  src/pages/Chat.tsx
  src/pages/Main.tsx
Labels: ✨ Feature

#31 [Set/#16] workflows로 cicd 추가
  .github/workflows/cicd.yml
Labels: ⚙ Setting

#32 [feat] 이미지 생성 기능구현
  src/api/images.ts
  src/components/ImageGenerateModal.tsx
  src/components/ImageGenerator.tsx
  src/pages/Chat.tsx
Labels: ✨ Feature, 🎨 Html&css, 🐞 BugFix

#35 [feat] 카카오톡 공유하기 기능 추가
  .pnp.cjs
  index.html
  share.js
  src/App.tsx
  src/components/PlayAudioPage.tsx
  src/pages/ListBoard.tsx
Labels: ✨ Feature

#37 [fix] TTS 스트림 재생 구현
  .pnp.cjs
  src/components/AudioPlayer.tsx
  src/pages/Chat.tsx
Labels: 🐞 BugFix

#38 [feat] 스트림 데이터에서 bubbleId 추출 기능구현
  src/pages/Chat.tsx
Labels: ✨ Feature

#43 [feat] 뒤로가기, 호버 기능 추가
  src/pages/ListBoard.tsx
Labels: ✨ Feature

#42 [feat] 이미지 생성시 서버에 업로드 기능구현
  src/api/images.ts
  src/api/voices.ts
  src/components/ImageGenerateModal.tsx
  src/components/ImageGenerator.tsx
  src/pages/Chat.tsx
Labels: ✨ Feature

#44 [feat] 카카오톡 음성 공유 기능 구현 및 UI 수정
  .pnp.cjs
  src/App.tsx
  src/components/PlayAudioPage.tsx
  src/pages/ListBoard.tsx
  src/pages/Play.tsx
Labels: ✨ Feature

#47 [fix] 채팅 2번 보내지는 버그 수정
  src/api/chat.ts
  src/pages/Chat.tsx
Labels: 🐞 BugFix

#49 [fix] TTS 스트림 오류 수정
  src/api/images.ts
  src/components/AudioPlayer.tsx
  src/pages/Chat.tsx
Labels: 🐞 BugFix

#53 [design] 메인페이지 디자인 디벨롭
  .pnp.cjs
  src/components/CharacterCard.tsx
  src/components/ImageSlide.tsx
  src/components/Navbar.tsx
  src/pages/Main.tsx
  src/styles/ImageSlide.css
  src/styles/Trainsition.css
Labels: 🎨 Html&css

#56 [feat} 음성 다운로드 구현
  .pnp.cjs
  package.json
  src/pages/ListBoard.tsx
  src/pages/Play.tsx
  tailwind.config.js
  yarn.lock
Labels: ✨ Feature

#58 [design] 대시보드 overview 탭 구현
  .pnp.cjs
  package.json
  src/App.tsx
  src/api/characters.ts
  src/components/Navbar.tsx
  src/pages/Chat.tsx
  src/pages/DashBoard.tsx
  tailwind.config.js
  yarn.lock
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#60 [design] 다운로드 목록 디자인 디벨롭
  .pnp.cjs
  src/pages/Chat.tsx
Labels: 🎨 Html&css

#63 [feat] 캐릭터별 대시보드 구현
  .pnp.cjs
  src/api/characters.ts
  src/components/Dial.tsx
  src/pages/Chat.tsx
  src/pages/DashBoard.tsx
  src/pages/ListBoard.tsx
  src/pages/Main.tsx
  src/pages/Play.tsx
Labels: ✨ Feature, 🐞 BugFix, 📬 API

#65 [fix] listboard 에러 수정
  .pnp.cjs
  src/pages/ListBoard.tsx
Labels: 🐞 BugFix

#69 [fix] 카카오 연동 에러 해결
  .pnp.cjs
  global.d.ts
  src/components/AudioPlayer.tsx
  src/pages/Chat.tsx
  src/pages/ListBoard.tsx
  src/pages/Main.tsx
  tsconfig.app.json
Labels: 🐞 BugFix

#71 [design] 메인페이지 반응형 디자인 적용
  src/components/CharacterCard.tsx
  src/components/Navbar.tsx
  src/pages/Main.tsx
Labels: 🎨 Html&css

#73 [design] 목록페이지 반응형 디자인 적용
  .pnp.cjs
  src/pages/ListBoard.tsx
Labels: 🎨 Html&css

#77 [design] 채팅페이지 반응형 디자인 적용
  .pnp.cjs
  src/components/CharacterCard.tsx
  src/components/Navbar.tsx
  src/pages/Chat.tsx
  src/pages/Main.tsx
Labels: 🎨 Html&css

#75 [Set/#38] cicd 설정 추가 완료
  .github/workflows/cicd.yml
Labels: ⚙ Setting, 🌏 Deploy

#79 [design] 목록페이지 반응형 디자인 수정
  src/pages/ListBoard.tsx
Labels: 🎨 Html&css

#80 [design] 대시보드 반응형 디자인 적용
  src/components/Dial.tsx
  src/pages/DashBoard.tsx
  src/pages/Main.tsx
Labels: 🎨 Html&css

#83 [design] 채팅페이지 반응형 디자인 적용
  src/App.tsx
  src/components/Card.tsx
  src/pages/Chat.tsx
  src/pages/ListBoard.tsx
  src/pages/Main.tsx
  src/pages/Test.tsx
  src/pages/Test2.tsx
  src/styles/card.css
  src/styles/test.css
Labels: 🎨 Html&css

#84 [set/#42] 마지막 env까지 추가 완
  .github/workflows/cicd.yml
Labels: ⚙ Setting, 🌏 Deploy

#87 [feat] 이미지 흑백 모드 변경 기능구현
  src/components/ImageGenerator.tsx
Labels: ✨ Feature

#89 [design] 음성공유 모바일 반응형 디자인 구현
  .pnp.cjs
  src/pages/Play.tsx
Labels: 🎨 Html&css

#95 [design] 전체 페이지 모바일 반응형 수정
  src/components/Navbar.tsx
  src/pages/DashBoard.tsx
  src/pages/ListBoard.tsx
  src/pages/Main.tsx
Labels: 🎨 Html&css

#96 [feat] TTS 다운로드시 API 중복요청 예외처리
  src/pages/Chat.tsx
Labels: ✨ Feature

#98 [design] 캐릭터 이미지 수정
  src/pages/Chat.tsx
  src/pages/Main.tsx
Labels: 🎨 Html&css

#101 [fix] 이미지 공유 -> 다운로드 변경
  src/pages/ListBoard.tsx
Labels: ✨ Feature
